<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $settings = [
            // オークション設定（不足分）
            [
                'setting_key' => 'price_increment_min',
                'setting_value' => '50',
                'value_type' => 'integer',
                'category' => 'auction',
                'display_name' => '最低上昇金額（円）',
                'description' => '価格上昇の最低金額',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'auto_extend_seconds',
                'setting_value' => '10',
                'value_type' => 'integer',
                'category' => 'auction',
                'display_name' => '自動延長秒数',
                'description' => '終了直前の入札で延長する秒数',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // 料金設定（不足分）
            [
                'setting_key' => 'seller_registration_fee',
                'setting_value' => '3000',
                'value_type' => 'integer',
                'category' => 'payment',
                'display_name' => '出品者登録料（初回）',
                'description' => '出品者登録時の初期費用',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'seller_annual_fee',
                'setting_value' => '0',
                'value_type' => 'integer',
                'category' => 'payment',
                'display_name' => '出品者年会費',
                'description' => '年間維持費（0で無料）',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'base_listing_fee',
                'setting_value' => '500',
                'value_type' => 'integer',
                'category' => 'payment',
                'display_name' => '基本出品料',
                'description' => '1点あたりの出品料',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'seller_commission_min',
                'setting_value' => '500',
                'value_type' => 'integer',
                'category' => 'payment',
                'display_name' => '出品者最低手数料',
                'description' => '1点あたりの最低手数料',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'buyer_registration_fee',
                'setting_value' => '0',
                'value_type' => 'integer',
                'category' => 'payment',
                'display_name' => '買受者登録料',
                'description' => '買受者登録時の費用（0で無料）',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'buyer_commission_rate',
                'setting_value' => '5',
                'value_type' => 'decimal',
                'category' => 'payment',
                'display_name' => '買受者落札手数料率（%）',
                'description' => '落札金額に対する手数料',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'buyer_commission_min',
                'setting_value' => '300',
                'value_type' => 'integer',
                'category' => 'payment',
                'display_name' => '買受者最低手数料',
                'description' => '1点あたりの最低手数料',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // 配送・梱包設定
            [
                'setting_key' => 'packaging_fee',
                'setting_value' => '500',
                'value_type' => 'integer',
                'category' => 'shipping',
                'display_name' => '梱包料金',
                'description' => '1件あたりの梱包費',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'handling_fee',
                'setting_value' => '300',
                'value_type' => 'integer',
                'category' => 'shipping',
                'display_name' => '取扱手数料',
                'description' => '発送事務手数料',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'insurance_fee_rate',
                'setting_value' => '3',
                'value_type' => 'decimal',
                'category' => 'shipping',
                'display_name' => '保険料率（%）',
                'description' => '落札金額に対する保険料',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'cooling_fee_summer',
                'setting_value' => '300',
                'value_type' => 'integer',
                'category' => 'shipping',
                'display_name' => '夏季クール便料金',
                'description' => '6-9月の追加料金',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'heating_fee_winter',
                'setting_value' => '300',
                'value_type' => 'integer',
                'category' => 'shipping',
                'display_name' => '冬季保温料金',
                'description' => '12-2月の追加料金',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'shipping_rates',
                'setting_value' => json_encode([
                    ['region' => '関東', 'size_60' => 800, 'size_80' => 1000, 'size_100' => 1200],
                    ['region' => '関西', 'size_60' => 900, 'size_80' => 1100, 'size_100' => 1300],
                    ['region' => '北海道', 'size_60' => 1500, 'size_80' => 1800, 'size_100' => 2100],
                    ['region' => '沖縄', 'size_60' => 1800, 'size_80' => 2200, 'size_100' => 2600],
                    ['region' => 'その他', 'size_60' => 1000, 'size_80' => 1200, 'size_100' => 1500],
                ]),
                'value_type' => 'json',
                'category' => 'shipping',
                'display_name' => '地域別配送料金',
                'description' => '地域とサイズ別の配送料金テーブル',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // 帳票設定
            [
                'setting_key' => 'company_name',
                'setting_value' => '株式会社メダカオークション',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '会社名・屋号',
                'description' => '帳票に表示する会社名',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'company_address',
                'setting_value' => '東京都渋谷区xxx 1-2-3',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '会社住所',
                'description' => '帳票に表示する住所',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'company_phone',
                'setting_value' => '03-1234-5678',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '会社電話番号',
                'description' => '帳票に表示する電話番号',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'company_email',
                'setting_value' => 'info@example.com',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '会社メールアドレス',
                'description' => '帳票に表示するメールアドレス',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'bank_name',
                'setting_value' => '三菱UFJ銀行',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '銀行名',
                'description' => '振込先銀行名',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'bank_branch',
                'setting_value' => '渋谷支店',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '支店名',
                'description' => '振込先支店名',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'bank_account_type',
                'setting_value' => '普通',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '口座種別',
                'description' => '口座種別（普通/当座）',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'bank_account_number',
                'setting_value' => '1234567',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '口座番号',
                'description' => '振込先口座番号',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'bank_account_holder',
                'setting_value' => 'カ）メダカオークション',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '口座名義',
                'description' => '振込先口座名義',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'invoice_prefix',
                'setting_value' => 'INV-',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '請求書プレフィックス',
                'description' => '請求書番号のプレフィックス',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'payment_notice_prefix',
                'setting_value' => 'PAY-',
                'value_type' => 'string',
                'category' => 'document',
                'display_name' => '支払通知書プレフィックス',
                'description' => '支払通知書番号のプレフィックス',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'warranty_validity_days',
                'setting_value' => '14',
                'value_type' => 'integer',
                'category' => 'document',
                'display_name' => '保証書有効日数',
                'description' => '到着後の保証期間（日数）',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'auto_generate_invoice',
                'setting_value' => '1',
                'value_type' => 'boolean',
                'category' => 'document',
                'display_name' => '請求書自動発行',
                'description' => '落札確定時に請求書を自動生成',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'auto_generate_payment_notice',
                'setting_value' => '1',
                'value_type' => 'boolean',
                'category' => 'document',
                'display_name' => '支払通知書自動発行',
                'description' => '入金確認時に支払通知書を自動生成',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // システム設定（不足分）
            [
                'setting_key' => 'business_hours',
                'setting_value' => '平日 10:00-18:00',
                'value_type' => 'string',
                'category' => 'site',
                'display_name' => '営業時間',
                'description' => '営業時間の表示',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_key' => 'contact_phone',
                'setting_value' => '03-1234-5678',
                'value_type' => 'string',
                'category' => 'site',
                'display_name' => '連絡先電話番号',
                'description' => '問い合わせ先電話番号',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($settings as $setting) {
            // 既存のキーがなければ挿入
            if (!DB::table('system_settings')->where('setting_key', $setting['setting_key'])->exists()) {
                DB::table('system_settings')->insert($setting);
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $keysToRemove = [
            'price_increment_min', 'auto_extend_seconds',
            'seller_registration_fee', 'seller_annual_fee', 'base_listing_fee',
            'seller_commission_min', 'buyer_registration_fee', 'buyer_commission_rate', 'buyer_commission_min',
            'packaging_fee', 'handling_fee', 'insurance_fee_rate', 'cooling_fee_summer', 'heating_fee_winter', 'shipping_rates',
            'company_name', 'company_address', 'company_phone', 'company_email',
            'bank_name', 'bank_branch', 'bank_account_type', 'bank_account_number', 'bank_account_holder',
            'invoice_prefix', 'payment_notice_prefix', 'warranty_validity_days',
            'auto_generate_invoice', 'auto_generate_payment_notice',
            'business_hours', 'contact_phone',
        ];
        
        DB::table('system_settings')->whereIn('setting_key', $keysToRemove)->delete();
    }
};
